apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hello-world-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: fkcurrie/hello-world-2
      ephemeral: true
      labels:
        - self-hosted
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        nameservers:
          - 10.152.183.10
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      dockerdWithinRunnerContainer: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock