name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        run: |
          docker build -t localhost:32000/fcurrie/hello-world-app:${{ github.sha }} .
          docker push localhost:32000/fcurrie/hello-world-app:${{ github.sha }}

      - name: Update deployment
        env:
          IMAGE_TAG: localhost:32000/fcurrie/hello-world-app:${{ github.sha }}
        run: |
          sed -i "s|image:.*|image: $IMAGE_TAG|" deployment.yaml
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add deployment.yaml
          git commit -m "Update deployment image to ${{ github.sha }}"
          git push origin main
